--
-- PostgreSQL database dump
--

\restrict LQdUsDtJdqgivLDvu51382nKf2HWuVXDbPcqrHH0ZO65yNNQjzvseQ2ggeMN1lt

-- Dumped from database version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)

-- Started on 2025-10-01 22:54:32 +06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 44099)
-- Name: kyc_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kyc_record (
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    email character varying(255),
    first_name character varying(255) NOT NULL,
    last_name character varying(255),
    phone character varying(255),
    photo_content_type character varying(255),
    photo_path character varying(255)
);


ALTER TABLE public.kyc_record OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 44098)
-- Name: kyc_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kyc_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 44109)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 44108)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 44117)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    active boolean NOT NULL,
    email_verified boolean,
    mobile_verified boolean,
    otp_code character varying(4),
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    otp_expires_at timestamp(6) without time zone,
    role_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    email character varying(255),
    mobile character varying(255),
    name character varying(255),
    password character varying(255),
    picture_url character varying(255),
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 44116)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3364 (class 0 OID 44099)
-- Dependencies: 210
-- Data for Name: kyc_record; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kyc_record (created_at, id, updated_at, email, first_name, last_name, phone, photo_content_type, photo_path) FROM stdin;
2025-10-01 16:29:12.47463+06	9	2025-10-01 16:29:12.474632+06	joh2n@example.com	John2	\N	1234567892	image/png	68f10fab-be41-4d03-abef-02306fb4f89d.png
2025-10-01 17:14:17.872498+06	10	2025-10-01 17:14:17.872499+06	joh2n@example.com	John2	\N	1234567892	image/png	25a91002-6a10-4663-8359-0005f5ff86f8.png
2025-10-01 17:44:30.492855+06	12	2025-10-01 17:44:30.492856+06	sd@3asd.kwe	klsa		1212	\N	\N
2025-10-01 19:45:24.124597+06	14	2025-10-01 19:45:24.124598+06	aaaa@lsd.caa	zakaria		902923	image/png	171f07b3-9265-4503-bdb4-4a4cfc986fc9.png
\.


--
-- TOC entry 3366 (class 0 OID 44109)
-- Dependencies: 212
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name) FROM stdin;
1	ROLE_STUDENT
\.


--
-- TOC entry 3368 (class 0 OID 44117)
-- Dependencies: 214
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (active, email_verified, mobile_verified, otp_code, created_at, id, otp_expires_at, role_id, updated_at, email, mobile, name, password, picture_url, username) FROM stdin;
t	f	f	AB41	\N	3	\N	1	2025-10-01 01:32:05.013256	\N	8801969037346	zakaria	$2a$12$P2hxDH2rRaTdF7lP1ssIbuV5miYIqaSqNAmFnlK9ERVIEK2k1vSti	\N	8801969037346
\.


--
-- TOC entry 3374 (class 0 OID 0)
-- Dependencies: 209
-- Name: kyc_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kyc_record_id_seq', 14, true);


--
-- TOC entry 3375 (class 0 OID 0)
-- Dependencies: 211
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, true);


--
-- TOC entry 3376 (class 0 OID 0)
-- Dependencies: 213
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- TOC entry 3216 (class 2606 OID 44105)
-- Name: kyc_record kyc_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kyc_record
    ADD CONSTRAINT kyc_record_pkey PRIMARY KEY (id);


--
-- TOC entry 3218 (class 2606 OID 44115)
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- TOC entry 3220 (class 2606 OID 44113)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3222 (class 2606 OID 44123)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3223 (class 2606 OID 44124)
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


-- Completed on 2025-10-01 22:54:32 +06

--
-- PostgreSQL database dump complete
--

\unrestrict LQdUsDtJdqgivLDvu51382nKf2HWuVXDbPcqrHH0ZO65yNNQjzvseQ2ggeMN1lt

