# ==============================
# Server
# ==============================
server.port=9100

# ==============================
# Spring Datasource (PostgreSQL)server.port=9100
# ==============================

#spring.datasource.url=jdbc:postgresql://localhost:5432/kyc_db
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# ===============================
# AUTH_DB DATABASE (PostgreSQL)
# ===============================
spring.datasource.auth.jdbc-url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.auth.username=postgres
spring.datasource.auth.password=123456
spring.datasource.auth.driver-class-name=org.postgresql.Driver


# ===============================
# KYC_DB DATABASE (PostgreSQL)
# ===============================
spring.datasource.kyc.jdbc-url=jdbc:postgresql://localhost:5433/kyc_db
spring.datasource.kyc.username=postgres
spring.datasource.kyc.password=123456
spring.datasource.kyc.driver-class-name=org.postgresql.Driver



# ===============================
# KYC_DB DATABASE (PostgreSQL)
# ===============================
spring.datasource.gis.jdbc-url=jdbc:postgresql://localhost:5433/gisdb
spring.datasource.gis.username=postgres
spring.datasource.gis.password=123456
spring.datasource.gis.driver-class-name=org.postgresql.Driver


# ==============================
# JWT Settings (Optional)
# ==============================

jwt.secret=492421df8dddfa71049356c47fc28d10f711c9171bde93e2552c5a2f637d7e53
jwt.expiration=1500000
#jwt.expiration=300000
jwt.refresh.expiration=9900000
jwt.allowed-clock-skew-seconds=60
#This means: If your server clock and the token issuer’s clock are slightly out of sync, valid tokens might get rejected. This setting prevents that
#A token that expired up to 60 seconds ago is still accepted
#A token that starts in up to 60 seconds in the future is still accepted

# ==============================
# Authentication Mode / Keycloak
# ==============================
app.auth.mode=${AUTH_MODE:SSO}
keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:9200/realms/kyc}
keycloak.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:9200/realms/kyc/protocol/openid-connect/certs}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:nexacore-client}
keycloak.allowed-client-ids=${KEYCLOAK_ALLOWED_CLIENT_IDS:nexacore-client,privilege-frontend}
keycloak.required-audience=${KEYCLOAK_AUDIENCE:nexacore}
keycloak.sync-user=${KEYCLOAK_SYNC_USER:true}
keycloak.default-role=${KEYCLOAK_DEFAULT_ROLE:ROLE_KYC_OPERATOR}

# ==============================
# CORS Settings (Optional)
# ==============================
cors.allowed-origins=http://localhost:4200,http://localhost:4300,http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# ==============================
# File Storage Configuration
# ==============================
#storage.type=${STORAGE_TYPE:fileSystem}
storage.type=${STORAGE_TYPE:minio}
storage.filesystem.base-dir=${UPLOAD_DIR:./uploads}
storage.filesystem.public-base-url=${STORAGE_FILESYSTEM_PUBLIC_BASE_URL:/uploads}
storage.minio.endpoint=${MINIO_ENDPOINT:http://127.0.0.1:9000}
storage.minio.public-base-url=${MINIO_PUBLIC_BASE_URL:http://127.0.0.1:9000}
storage.minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
storage.minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
storage.minio.bucket=${MINIO_BUCKET:kyc-files}
storage.minio.auto-create-bucket=${MINIO_AUTO_CREATE_BUCKET:true}

# ==============================
# Swagger / OpenAPI
# ==============================
app.swaggerUrl=:9100/pilot/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==============================
# Multipart Enable
# ==============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
