-- Phase 1: additive foundation for Auth-owned global persons and tenant accounts.
-- Legacy global user constraints and lookup behavior intentionally remain in place.

CREATE TABLE auth_persons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    middle_name varchar(100),
    last_name varchar(100),
    date_of_birth date,
    gender varchar(30),
    blood_group varchar(10),
    primary_email varchar(254),
    primary_mobile varchar(30),
    email_verified boolean NOT NULL DEFAULT false,
    mobile_verified boolean NOT NULL DEFAULT false,
    status varchar(30) NOT NULL DEFAULT 'ACTIVE',
    active boolean NOT NULL DEFAULT true,
    created_by bigint NOT NULL DEFAULT 0,
    updated_by bigint NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_auth_person_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'MERGED', 'DECEASED'))
);

CREATE INDEX idx_auth_persons_status_active
    ON auth_persons(status, active);

CREATE INDEX idx_auth_persons_primary_email
    ON auth_persons(LOWER(primary_email))
    WHERE primary_email IS NOT NULL;

CREATE INDEX idx_auth_persons_primary_mobile
    ON auth_persons(primary_mobile)
    WHERE primary_mobile IS NOT NULL;

ALTER TABLE auth_users
    ADD COLUMN tenant_id bigint,
    ADD COLUMN normalized_username varchar(150),
    ADD COLUMN locked boolean NOT NULL DEFAULT false,
    ADD COLUMN password_changed_at timestamp,
    ADD COLUMN credentials_expire_at timestamp,
    ADD COLUMN created_by bigint NOT NULL DEFAULT 0,
    ADD COLUMN updated_by bigint NOT NULL DEFAULT 0;

-- These partial indexes prepare tenant-aware writes without weakening or replacing
-- the currently deployed global username/person indexes.
CREATE UNIQUE INDEX ux_auth_users_tenant_person_phase1
    ON auth_users(tenant_id, person_id)
    WHERE tenant_id IS NOT NULL;

CREATE UNIQUE INDEX ux_auth_users_tenant_username_phase1
    ON auth_users(tenant_id, normalized_username)
    WHERE tenant_id IS NOT NULL AND normalized_username IS NOT NULL;

CREATE UNIQUE INDEX ux_auth_users_tenant_external_identity_phase1
    ON auth_users(tenant_id, external_provider, external_subject)
    WHERE tenant_id IS NOT NULL
      AND external_provider IS NOT NULL
      AND external_subject IS NOT NULL;

ALTER TABLE auth_users
    ADD CONSTRAINT uk_auth_users_id_tenant UNIQUE (id, tenant_id);

ALTER TABLE auth_roles
    ADD COLUMN tenant_id bigint,
    ADD COLUMN role_code varchar(100),
    ADD COLUMN description varchar(255),
    ADD COLUMN active boolean NOT NULL DEFAULT true,
    ADD COLUMN created_by bigint NOT NULL DEFAULT 0,
    ADD COLUMN updated_by bigint NOT NULL DEFAULT 0,
    ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Existing global name uniqueness remains. These indexes express the target scopes
-- additively and become authoritative only after the later constraint cutover.
CREATE UNIQUE INDEX ux_auth_roles_global_name_phase1
    ON auth_roles(LOWER(name))
    WHERE tenant_id IS NULL;

CREATE UNIQUE INDEX ux_auth_roles_tenant_name_phase1
    ON auth_roles(tenant_id, LOWER(name))
    WHERE tenant_id IS NOT NULL;

CREATE UNIQUE INDEX ux_auth_roles_global_code_phase1
    ON auth_roles(LOWER(role_code))
    WHERE tenant_id IS NULL AND role_code IS NOT NULL;

CREATE UNIQUE INDEX ux_auth_roles_tenant_code_phase1
    ON auth_roles(tenant_id, LOWER(role_code))
    WHERE tenant_id IS NOT NULL AND role_code IS NOT NULL;

CREATE INDEX idx_auth_roles_tenant_active
    ON auth_roles(tenant_id, active);
